### ISSUE TITLE
How is the solution generated in dataset5k?

### ISSUE THREAD

**Issue by Henryabgaryan** [AndreaCorsini1/SelfLabelingJobShop#1]
Hello, thank you for great work. I would like to know how are the makspans in dataset5k generated, and the sample solution after the makespan? And do the makspans correspond to the solution sequence?

**Comment by AndreaCorsini1** [comment]
Hello, I'm happy you enjoyed our work. The makespan of instances in dataset5k is the best found by our proposed model during the various trainings. You find the solution giving that makespan at the bottom of each file. Hope this answers you. I'll add a description in the README.

**Comment by AndreaCorsini1** [comment]
Closing this. Please feel free to reopen if there is any further clarification needed.
